"use strict";

const questions = [
  {
    question: "Which keyword is used to inherit a class in Java?",
    options: ["implements", "extends", "inherits", "super"],
    correctAnswer: 1,
    category: "Java",
    difficulty: "Easy",
    explanation: "The extends keyword is used for class inheritance in Java.",
  },
  {
    question: "Which Java collection stores unique values?",
    options: ["List", "Set", "ArrayList", "Queue"],
    correctAnswer: 1,
    category: "Java",
    difficulty: "Easy",
    explanation: "A Set does not allow duplicate elements.",
  },
  {
    question: "Which method starts a Java thread?",
    options: ["run()", "execute()", "start()", "begin()"],
    correctAnswer: 2,
    category: "Java",
    difficulty: "Medium",
    explanation:
      "Calling start() creates a new thread and then invokes its run() method.",
  },
  {
    question: "Which Java keyword prevents a class from being inherited?",
    options: ["static", "private", "final", "protected"],
    correctAnswer: 2,
    category: "Java",
    difficulty: "Medium",
    explanation: "A final class cannot be extended.",
  },
  {
    question: "Which Java exception is unchecked?",
    options: [
      "IOException",
      "SQLException",
      "ClassNotFoundException",
      "NullPointerException",
    ],
    correctAnswer: 3,
    category: "Java",
    difficulty: "Medium",
    explanation:
      "NullPointerException extends RuntimeException and is unchecked.",
  },

  {
    question: "Which keyword defines a function in Python?",
    options: ["function", "func", "def", "define"],
    correctAnswer: 2,
    category: "Python",
    difficulty: "Easy",
    explanation: "Python functions are declared using the def keyword.",
  },
  {
    question: "Which Python data type is immutable?",
    options: ["List", "Dictionary", "Set", "Tuple"],
    correctAnswer: 3,
    category: "Python",
    difficulty: "Easy",
    explanation: "A tuple cannot be modified after creation.",
  },
  {
    question: "What does len([10, 20, 30]) return?",
    options: ["2", "3", "30", "60"],
    correctAnswer: 1,
    category: "Python",
    difficulty: "Easy",
    explanation: "The list contains three elements.",
  },
  {
    question: "Which operator performs floor division in Python?",
    options: ["/", "//", "%", "**"],
    correctAnswer: 1,
    category: "Python",
    difficulty: "Medium",
    explanation: "The // operator performs floor division.",
  },
  {
    question: "Which Python statement handles exceptions?",
    options: ["if-else", "switch-case", "try-except", "check-catch"],
    correctAnswer: 2,
    category: "Python",
    difficulty: "Easy",
    explanation: "Python uses try and except blocks for exception handling.",
  },

  {
    question: "Which symbol terminates most C statements?",
    options: [":", ".", ";", ","],
    correctAnswer: 2,
    category: "C",
    difficulty: "Easy",
    explanation: "Most C statements end with a semicolon.",
  },
  {
    question: "Which function prints formatted output in C?",
    options: ["print()", "printf()", "cout", "write()"],
    correctAnswer: 1,
    category: "C",
    difficulty: "Easy",
    explanation: "printf() is declared in stdio.h.",
  },
  {
    question: "Which operator obtains the address of a variable in C?",
    options: ["*", "&", "%", "#"],
    correctAnswer: 1,
    category: "C",
    difficulty: "Medium",
    explanation: "The address-of operator is &.",
  },
  {
    question: "Which function dynamically allocates memory in C?",
    options: ["alloc()", "new()", "malloc()", "create()"],
    correctAnswer: 2,
    category: "C",
    difficulty: "Medium",
    explanation: "malloc() allocates memory dynamically.",
  },
  {
    question: "Which header file declares malloc()?",
    options: ["stdio.h", "string.h", "stdlib.h", "math.h"],
    correctAnswer: 2,
    category: "C",
    difficulty: "Medium",
    explanation: "malloc() is declared in stdlib.h.",
  },

  {
    question: "Which SQL command retrieves rows from a table?",
    options: ["GET", "OPEN", "SELECT", "FETCH TABLE"],
    correctAnswer: 2,
    category: "DBMS",
    difficulty: "Easy",
    explanation: "SELECT is used to retrieve data from database tables.",
  },
  {
    question: "Which key uniquely identifies a table row?",
    options: ["Foreign key", "Primary key", "Composite value", "Index key"],
    correctAnswer: 1,
    category: "DBMS",
    difficulty: "Easy",
    explanation: "A primary key uniquely identifies each row.",
  },
  {
    question: "Which normal form removes partial dependency?",
    options: ["1NF", "2NF", "3NF", "BCNF"],
    correctAnswer: 1,
    category: "DBMS",
    difficulty: "Medium",
    explanation:
      "Second Normal Form removes partial dependency on a composite key.",
  },
  {
    question: "Which SQL clause filters rows?",
    options: ["ORDER BY", "GROUP BY", "WHERE", "JOIN"],
    correctAnswer: 2,
    category: "DBMS",
    difficulty: "Easy",
    explanation: "The WHERE clause filters rows according to a condition.",
  },
  {
    question: "Which operation combines rows from related tables?",
    options: ["JOIN", "DELETE", "DROP", "TRUNCATE"],
    correctAnswer: 0,
    category: "DBMS",
    difficulty: "Easy",
    explanation: "JOIN combines related rows from two or more tables.",
  },

  {
    question: "Which operating system component manages hardware resources?",
    options: ["Compiler", "Kernel", "Browser", "Editor"],
    correctAnswer: 1,
    category: "Operating Systems",
    difficulty: "Easy",
    explanation: "The kernel manages CPU, memory, devices, and processes.",
  },
  {
    question: "Which scheduling algorithm executes processes in arrival order?",
    options: ["SJF", "Round Robin", "FCFS", "Priority"],
    correctAnswer: 2,
    category: "Operating Systems",
    difficulty: "Easy",
    explanation: "FCFS means First Come, First Served.",
  },
  {
    question: "Which memory technique divides memory into fixed-size blocks?",
    options: ["Segmentation", "Paging", "Compaction", "Swapping"],
    correctAnswer: 1,
    category: "Operating Systems",
    difficulty: "Medium",
    explanation:
      "Paging divides logical memory into pages and physical memory into frames.",
  },
  {
    question: "Which condition is necessary for deadlock?",
    options: [
      "Preemption",
      "Circular wait",
      "Unlimited resources",
      "Single process",
    ],
    correctAnswer: 1,
    category: "Operating Systems",
    difficulty: "Medium",
    explanation:
      "Circular wait is one of the four necessary deadlock conditions.",
  },
  {
    question: "What is a page fault?",
    options: [
      "A syntax error",
      "A missing page in main memory",
      "A disk formatting error",
      "A CPU failure",
    ],
    correctAnswer: 1,
    category: "Operating Systems",
    difficulty: "Medium",
    explanation:
      "A page fault occurs when a referenced page is not currently in physical memory.",
  },

  {
    question: "Which protocol is used to load web pages?",
    options: ["FTP", "HTTP", "SMTP", "SSH"],
    correctAnswer: 1,
    category: "Computer Networks",
    difficulty: "Easy",
    explanation: "HTTP is used to transfer web resources.",
  },
  {
    question: "Which device forwards packets between networks?",
    options: ["Hub", "Switch", "Router", "Repeater"],
    correctAnswer: 2,
    category: "Computer Networks",
    difficulty: "Easy",
    explanation: "A router forwards packets between different networks.",
  },
  {
    question: "How many bits are in an IPv4 address?",
    options: ["16", "32", "64", "128"],
    correctAnswer: 1,
    category: "Computer Networks",
    difficulty: "Easy",
    explanation: "An IPv4 address contains 32 bits.",
  },
  {
    question: "Which protocol translates domain names into IP addresses?",
    options: ["DNS", "DHCP", "ARP", "TCP"],
    correctAnswer: 0,
    category: "Computer Networks",
    difficulty: "Easy",
    explanation: "DNS resolves domain names to IP addresses.",
  },
  {
    question: "Which transport protocol provides reliable delivery?",
    options: ["UDP", "IP", "TCP", "ICMP"],
    correctAnswer: 2,
    category: "Computer Networks",
    difficulty: "Medium",
    explanation: "TCP provides ordered and reliable data delivery.",
  },
];

module.exports = questions;
